// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Adminbot.Migrations
{
    [DbContext(typeof(UserDbContext))]
    [Migration("20260630132823_AddGozargahSiteSyncOutbox")]
    partial class AddGozargahSiteSyncOutbox
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("Adminbot.Domain.BotInstance", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("AndroidTutorialJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("BackupChannel")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("BrandName")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ChannelIdsJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IosTutorialJson")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LoggerChannel")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long?>("OwnerTelegramUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SupportAccount")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantCardHolderName")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantCardNumber")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("TenantCardPaymentEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenantChannelIdsJson")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TenantHooshPayEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TenantMandatoryJoinEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TenantNowPaymentsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TenantPriceMarkupPercent")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenantTutorialsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantWelcomeText")
                        .HasColumnType("TEXT");

                    b.Property<string>("Token")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("WindowsTutorialJson")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OwnerTelegramUserId");

                    b.HasIndex("Username");

                    b.ToTable("BotInstances", (string)null);
                });

            modelBuilder.Entity("Adminbot.Domain.BotUserState", b =>
                {
                    b.Property<string>("BotId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("TelegramUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountCounter")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConfigLink")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Flow")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastFreeAcc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastFreeNationalAcc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastFreeNormalAcc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastStep")
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("PendingAccountCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PendingUserComment")
                        .HasColumnType("TEXT");

                    b.Property<string>("SelectedCountry")
                        .HasColumnType("TEXT");

                    b.Property<string>("SelectedPeriod")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubLink")
                        .HasColumnType("TEXT");

                    b.Property<string>("TotoalGB")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("_ConfigPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("BotId", "TelegramUserId");

                    b.HasIndex("Flow");

                    b.HasIndex("TelegramUserId");

                    b.ToTable("BotUserStates", (string)null);
                });

            modelBuilder.Entity("Adminbot.Domain.GozargahSiteSyncEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BotId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long?>("BuyerTelegramUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT");

                    b.Property<string>("Operation")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<long?>("OwnerTelegramUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PreviousEmail")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResponseJson")
                        .HasColumnType("TEXT");

                    b.Property<int>("RetryCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SiteOrderId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("SubId")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("SubLink")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SucceededAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("TelegramUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenantBotId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Uuid")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BotId");

                    b.HasIndex("BuyerTelegramUserId");

                    b.HasIndex("Email");

                    b.HasIndex("OwnerTelegramUserId");

                    b.HasIndex("Status");

                    b.HasIndex("SubId");

                    b.HasIndex("TelegramUserId");

                    b.HasIndex("TenantBotId");

                    b.HasIndex("Uuid");

                    b.HasIndex("Operation", "Email", "PreviousEmail", "Uuid", "SubId");

                    b.ToTable("GozargahSiteSyncEvents", (string)null);
                });

            modelBuilder.Entity("Adminbot.Domain.HooshPayPaymentInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AmountToman")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("BalanceAfter")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("BalanceBefore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BotId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("BotUsername")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long>("ChatId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<long>("FeeAmountToman")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FeeMode")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("FeePercent")
                        .HasColumnType("TEXT");

                    b.Property<string>("InvoiceUid")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("IpnCallbackUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAddedToBalance")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MerchantCreditToman")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PaidAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("PayableAmountToman")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PaymentPurpose")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentStatus")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("RawIpnJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("RawRequestJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("RawResponseJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReturnUrl")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SettledAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<long?>("TelMsgId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TelegramUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TenantBotOrderId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("TenantOwnerTelegramUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TrackingCode")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BotId");

                    b.HasIndex("ChatId");

                    b.HasIndex("InvoiceUid");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.HasIndex("PaymentPurpose");

                    b.HasIndex("TelegramUserId");

                    b.HasIndex("TenantBotOrderId");

                    b.HasIndex("TenantOwnerTelegramUserId");

                    b.ToTable("HooshPayPaymentInfos", (string)null);
                });

            modelBuilder.Entity("Adminbot.Domain.SwapinoPaymentInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ActuallyPaid")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ActuallyPaidAtFiat")
                        .HasColumnType("TEXT");

                    b.Property<long>("AmountToman")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AttemptNo")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("BalanceAfter")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("BalanceBefore")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("BaseAmount")
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseCurrency")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("BotId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("BotUsername")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("CancelUrl")
                        .HasColumnType("TEXT");

                    b.Property<long>("ChatId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("InvoiceId")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("InvoiceUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("IpnCallbackUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAddedToBalance")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OutcomeAmount")
                        .HasColumnType("TEXT");

                    b.Property<string>("OutcomeCurrency")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PaidAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ParentOrderId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ParentPaymentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PayAddress")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PayCurrency")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("PayinHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentId")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentPurpose")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentStatus")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("PayoutHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("RawIpnJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("RawRequestJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("RawResponseJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Result")
                        .HasColumnType("TEXT");

                    b.Property<string>("RootOrderId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SettledAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("SuccessUrl")
                        .HasColumnType("TEXT");

                    b.Property<long?>("TelMsgId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TelegramUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TenantBotOrderId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("TenantOwnerTelegramUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BotId");

                    b.HasIndex("ChatId");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.HasIndex("ParentOrderId");

                    b.HasIndex("PaymentId");

                    b.HasIndex("PaymentPurpose");

                    b.HasIndex("TelegramUserId");

                    b.HasIndex("TenantBotOrderId");

                    b.ToTable("SwapinoPaymentInfos", (string)null);
                });

            modelBuilder.Entity("Adminbot.Domain.TenantBotLedgerEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("BaseCostToman")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("CustomerTelegramUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderId")
                        .HasMaxLength(140)
                        .HasColumnType("TEXT");

                    b.Property<long?>("OwnerBalanceAfter")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("OwnerBalanceBefore")
                        .HasColumnType("INTEGER");

                    b.Property<long>("OwnerTelegramUserId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ProfitToman")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SalePriceToman")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenantBotId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("TenantBotOrderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenantBotUsername")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CustomerTelegramUserId");

                    b.HasIndex("OwnerTelegramUserId");

                    b.HasIndex("TenantBotId");

                    b.HasIndex("TenantBotOrderId")
                        .IsUnique();

                    b.ToTable("TenantBotLedgerEntries", (string)null);
                });

            modelBuilder.Entity("Adminbot.Domain.TenantBotOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("BaseCostToman")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedAccountEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAccountJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedSubLink")
                        .HasColumnType("TEXT");

                    b.Property<long>("CustomerChatId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomerFirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerLastName")
                        .HasColumnType("TEXT");

                    b.Property<long>("CustomerTelegramUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomerUsername")
                        .HasColumnType("TEXT");

                    b.Property<string>("DurationKey")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FulfilledAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("FulfillmentSource")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("HooshPayInvoiceUid")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int?>("HooshPayPaymentInfoId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFulfilled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsOwnerCredited")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ManualReceiptId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("NowPaymentsPaymentInfoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderKind")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<long?>("OwnerBalanceAfter")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("OwnerBalanceBefore")
                        .HasColumnType("INTEGER");

                    b.Property<long>("OwnerTelegramUserId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("OwnerWalletDelta")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("PaidAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentProvider")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentStatus")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentUrl")
                        .HasColumnType("TEXT");

                    b.Property<long>("ProfitToman")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SalePriceToman")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ServiceKey")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetAccountEmail")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantBotId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantBotUsername")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int?>("TrafficGb")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UnlimitedPlanKey")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserComment")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CustomerTelegramUserId");

                    b.HasIndex("HooshPayPaymentInfoId");

                    b.HasIndex("ManualReceiptId");

                    b.HasIndex("NowPaymentsPaymentInfoId");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.HasIndex("OrderKind");

                    b.HasIndex("OwnerTelegramUserId");

                    b.HasIndex("TenantBotId");

                    b.ToTable("TenantBotOrders", (string)null);
                });

            modelBuilder.Entity("Adminbot.Domain.TenantManualPaymentReceipt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AmountToman")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ApprovedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("CustomerChatId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CustomerTelegramUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FinalConfirmedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderId")
                        .HasMaxLength(140)
                        .HasColumnType("TEXT");

                    b.Property<long>("OwnerTelegramUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PhotoFileId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RejectedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ReviewerTelegramUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantBotId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("TenantBotOrderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenantBotUsername")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CustomerTelegramUserId");

                    b.HasIndex("OwnerTelegramUserId");

                    b.HasIndex("Status");

                    b.HasIndex("TenantBotId");

                    b.HasIndex("TenantBotOrderId");

                    b.ToTable("TenantManualPaymentReceipts", (string)null);
                });

            modelBuilder.Entity("Adminbot.Domain.WalletLedgerEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AmountToman")
                        .HasColumnType("INTEGER");

                    b.Property<long>("BalanceAfter")
                        .HasColumnType("INTEGER");

                    b.Property<long>("BalanceBefore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BotId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("BotType")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("BotUsername")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long?>("CounterpartyTelegramUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Direction")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderId")
                        .HasMaxLength(140)
                        .HasColumnType("TEXT");

                    b.Property<long?>("OwnerTelegramUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Provider")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferenceId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferenceType")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("TelegramUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BotId");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("OrderId");

                    b.HasIndex("OwnerTelegramUserId");

                    b.HasIndex("TelegramUserId");

                    b.ToTable("WalletLedgerEntries", (string)null);
                });

            modelBuilder.Entity("Adminbot.Domain.ZibalPaymentInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AttemptsRemaining")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BotId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("BotUsername")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("CallbackUrl")
                        .HasColumnType("TEXT");

                    b.Property<long>("ChatId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAddedToBallance")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsExpired")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PaidAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Result")
                        .HasColumnType("TEXT");

                    b.Property<long>("TelMsgId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TelegramUserId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TrackId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BotId");

                    b.ToTable("ZibalPaymentInfos");
                });

            modelBuilder.Entity("CookieData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ExpirationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionCookie")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cookies");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountCounter")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConfigLink")
                        .HasColumnType("TEXT");

                    b.Property<long>("ConfigPrice")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Flow")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastFreeAcc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastFreeNationalAcc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastFreeNormalAcc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastStep")
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("TEXT");

                    b.Property<int>("PendingAccountCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PendingUserComment")
                        .HasColumnType("TEXT");

                    b.Property<string>("SelectedCountry")
                        .HasColumnType("TEXT");

                    b.Property<string>("SelectedPeriod")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubLink")
                        .HasColumnType("TEXT");

                    b.Property<string>("TotoalGB")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.Property<string>("_ConfigPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
