// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Adminbot.Migrations
{
    [DbContext(typeof(UserDbContext))]
    partial class UserDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Adminbot.Domain.SwapinoPaymentInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AmountToman")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ActuallyPaid")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ActuallyPaidAtFiat")
                        .HasColumnType("TEXT");

                    b.Property<int>("AttemptNo")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("BalanceAfter")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("BalanceBefore")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("BaseAmount")
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseCurrency")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("CancelUrl")
                        .HasColumnType("TEXT");

                    b.Property<long>("ChatId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("InvoiceId")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("InvoiceUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAddedToBalance")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IpnCallbackUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("OutcomeCurrency")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OutcomeAmount")
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("ParentOrderId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ParentPaymentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PayAddress")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PaidAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("PayCurrency")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("PayinHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentId")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentStatus")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("PayoutHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("RawIpnJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("RawRequestJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("RawResponseJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Result")
                        .HasColumnType("TEXT");

                    b.Property<string>("RootOrderId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SuccessUrl")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SettledAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<long?>("TelMsgId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TelegramUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.HasIndex("ParentOrderId");

                    b.HasIndex("PaymentId");

                    b.HasIndex("TelegramUserId");

                    b.ToTable("SwapinoPaymentInfos");
                });

            modelBuilder.Entity("Adminbot.Domain.ZibalPaymentInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AttemptsRemaining")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CallbackUrl")
                        .HasColumnType("TEXT");

                    b.Property<long>("ChatId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAddedToBallance")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsExpired")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PaidAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Result")
                        .HasColumnType("TEXT");

                    b.Property<long>("TelMsgId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TelegramUserId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TrackId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ZibalPaymentInfos");
                });

            modelBuilder.Entity("CookieData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ExpirationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionCookie")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cookies");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountCounter")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConfigLink")
                        .HasColumnType("TEXT");

                    b.Property<long>("ConfigPrice")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Flow")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastFreeAcc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastFreeNationalAcc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastFreeNormalAcc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastStep")
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("TEXT");

                    b.Property<int>("PendingAccountCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PendingUserComment")
                        .HasColumnType("TEXT");

                    b.Property<string>("SelectedCountry")
                        .HasColumnType("TEXT");

                    b.Property<string>("SelectedPeriod")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubLink")
                        .HasColumnType("TEXT");

                    b.Property<string>("TotoalGB")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.Property<string>("_ConfigPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
