// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Adminbot.Migrations.CredentialsDb
{
    [DbContext(typeof(CredentialsDbContext))]
    [Migration("20260905211658_AddWalletApprovalEvidence")]
    partial class AddWalletApprovalEvidence
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("Adminbot.Domain.CredUser", b =>
                {
                    b.Property<long>("TelegramUserId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("AccountBalance")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("BlockedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<long?>("BlockedByTelegramUserId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ChatID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsColleague")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LanguageCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("TelegramUserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Adminbot.Domain.WalletOperation", b =>
                {
                    b.Property<string>("OperationKey")
                        .HasMaxLength(240)
                        .HasColumnType("TEXT");

                    b.Property<long>("AfterBalance")
                        .HasColumnType("INTEGER");

                    b.Property<long>("AmountToman")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApprovalKind")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ApprovedByTelegramUserId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("BeforeBalance")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BotId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReconciledAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("TelegramUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("OperationKey");

                    b.HasIndex("TelegramUserId");

                    b.HasIndex("ReconciledAtUtc", "CreatedAtUtc");

                    b.ToTable("WalletOperations");
                });
#pragma warning restore 612, 618
        }
    }
}
